import comp from "C:/Users/muysengly/Desktop/My Github/blog/src/.vuepress/.temp/pages/classes/course_001/027.html.vue"
const data = JSON.parse("{\"path\":\"/classes/course_001/027.html\",\"title\":\"27. GUI Programming (Tkinter)\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"27. GUI Programming (Tkinter)\",\"description\":\"Python provides\",\"lead\":\"\",\"date\":\"2022-01-25T13:41:39.000Z\",\"lastmod\":\"2022-01-25T13:41:39.000Z\",\"draft\":false,\"images\":[],\"type\":\"docs\",\"toc\":true,\"weight\":27,\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/classes/course_001/027.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"My Website\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"27. GUI Programming (Tkinter)\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Python provides\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-25T13:41:39.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"27. GUI Programming (Tkinter)\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-01-25T13:41:39.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Sengly MUY\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Tkinter Programming\",\"slug\":\"tkinter-programming\",\"link\":\"#tkinter-programming\",\"children\":[]},{\"level\":2,\"title\":\"Example\",\"slug\":\"example\",\"link\":\"#example\",\"children\":[]},{\"level\":2,\"title\":\"Tkinter Widgets\",\"slug\":\"tkinter-widgets\",\"link\":\"#tkinter-widgets\",\"children\":[]},{\"level\":2,\"title\":\"Standard attributes\",\"slug\":\"standard-attributes\",\"link\":\"#standard-attributes\",\"children\":[]},{\"level\":2,\"title\":\"Geometry Management\",\"slug\":\"geometry-management\",\"link\":\"#geometry-management\",\"children\":[]}],\"readingTime\":{\"minutes\":3.04,\"words\":913},\"filePathRelative\":\"classes/course_001/027.md\",\"localizedDate\":\"January 25, 2022\",\"excerpt\":\"<p>Python provides various options for developing graphical user interfaces (GUIs). Most important are listed below.</p>\\n<ul>\\n<li><strong>Tkinter</strong> − Tkinter is the Python interface to the Tk GUI toolkit shipped with Python. We would look this option in this chapter.</li>\\n<li><strong>wxPython</strong> − This is an open-source Python interface for wxWindows <a href=\\\"http://wxpython.org/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">http://wxpython.org</a>.</li>\\n<li><strong>JPython</strong> − JPython is a Python port for Java which gives Python scripts seamless access to Java class libraries on the local machine <a href=\\\"http://www.jython.org/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">http://www.jython.org</a>.</li>\\n</ul>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
